### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by koufopoulosf** [mactrem/cov-tiles#1]
Hello,

I am a huge fan of your work and I would like to thank you for your valuable contribution!

I am making this issue as I would like to ask you two questions:

1.  Do you consider this production ready (I made the same question [here](https://github.com/mactrem/com-tiles/issues/17)) using maplibre-gl-js and S3 ?

2. If someone wants to serve a customizable (e.g. via maputnik) basemap like this ( https://maps.ckochis.com/styles/basic-preview/?vector - this is in MBTiles format), which one would you recommend as a better alternative, that could potentially be used by S3 for a vector basemap? PM-Tiles, COM-Tiles or COV-Tiles? What are the differences and use cases between COM-Tiles and COV-Tiles?

Thank you very much for your valuable time and I would love to read your feedback.

Best Regards,

Filippos

**Comment by mactrem** [comment]
Hi Filippos,

no, it's currently not production ready. 
It's part of a research of how the next generation of vector tiles could look like.
COVTiles is a optimized version of the Mapbox Vector Tiles spec in terms of the size of the tiles and hopefully also regarding the decoding performance. It also should add additional features like 3d coordinates or per vertex properties which are currently missing in the MVT spec. 
COMTiles on the other hand is a container format for tiles like a MBTiles for the cloud. In the future COVTiles could be combined with COMTiles for efficiently serving vector tiles from a cloud object storage.

**Comment by koufopoulosf** [comment]
Hi,

Thank you for your valuable feedback. These projects seem interesting and inspiring! Keep it up!

Thank you!

Best Regards,

Filippos
